### ISSUE TITLE
Pickle error

### ISSUE THREAD

**Issue by maxjaritz** [Cuberick-Orion/CIRPLANT#10]
Hi!
I could load the provided resnet image features without problem. However, I get the following error when trying load the Oscar features.

```
    pickle.load(open(img_feat_path, "rb"))
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```

Do I need to specify a loading function?

My goal is to reproduce your results in the paper (table 3). Are you using Oscar features for line image only?

Best,
Max

**Comment by Cuberick-Orion** [comment]
Hi Max,

If memory serves, I believe the files shall be loaded via `torch.load()` instead of `pickle` (yes, the file name ends in `.pkl` which is a bit confusing.

Best,
David.

**Comment by maxjaritz** [comment]
Thanks that works!
