### ISSUE TITLE
which version of transformers to use ?? 

### ISSUE THREAD

**Issue by complete-dope** [Cuberick-Orion/CIRPLANT#9]
I am unable to import transformers.pytorch_transformers 

Please provide a compatible version in the requirements file

**Comment by Cuberick-Orion** [comment]
Hi,

`transformers` is not a package to be installed via `pip` (though I am aware that there is a package with the same name), it is a module inside OSCAR, as below:

```python
(Pdb++) transformers.__path__
_NamespacePath(['<some directory>/Oscar/transformers'])

(Pdb++) transformers.pytorch_transformers.__path__
['<some directory>/Oscar/transformers/pytorch_transformers']

(Pdb++) from transformers.pytorch_transformers import AdamW, WarmupLinearSchedule
# no error, imported successfully
```

For details on the OSCAR version, see [this issue](https://github.com/Cuberick-Orion/CIRPLANT/issues/2#issuecomment-997901097).
